[[pages]]
path="src/Home.py"
name="Home"
icon="ğŸ "

[[pages]]
path="src/app_pages/00_Prompt_Iterator.py"
name="Prompt Iterator"
icon="ğŸ§™ğŸ»â€â™€ï¸"

[[pages]]
path="src/app_pages/01_Pinpoint_Segment.py"
name="Amazon Pinpoint Segment"
icon=":bar_chart:"

[[pages]]
path="src/app_pages/02_Personalize_Segment.py"
name="Amazon Personalize Segment"
icon=":white_check_mark:"

[[pages]]
path="src/app_pages/03_Content_Generator.py"
name="1:1 Content Generator"
icon="ğŸª„"



